# Configuration of Hugo
# Guide: https://gohugo.io/getting-started/configuration/
# Theme: https://github.com/CaiJimmy/hugo-theme-stack

title: 'My Personal Blog'
baseURL: 'https://praynpush.github.io/'
theme: hugo-theme-stack

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: false
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
    noClasses: false
