############################
## STACK THEME PARAMS
############################

mainSections:
  - blog

rssFullContent: true

dateFormat:
  published: "2006-01-02"
  lastUpdated: "2006-01-02"

article:
  headingAnchor: false
  math: false
  toc: true
  readingTime: true
  list:
    showTags: true
  license:
    enabled: false

widgets:
  homepage: []
  page: []

colorScheme:
  toggle: true
  default: auto

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

comments:
  enabled: false
  provider: ""
