mainSections   = ["blog"]
rssFullContent = true

[footer]
    since      = 2026
    customText = ""

# favicon  = "avatar.png"

[sidebar]
    compact  = false
    subtitle = "探索生活与健康"
    avatar   = "avatar.png"
    emoji    = "🌿"

[article]
    headingAnchor = false
    math          = false
    toc           = true
    readingTime   = true

    [article.list]
        showTags = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "tag-cloud", params = { limit = 20 } },
    ]
    page = [
        { type = "search" },
        { type = "toc" }
    ]

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing]
    cover = { enabled = true }
    content = { enabled = true }

[comments]
    enabled  = false
    provider = ""

[opengraph]
    defaultImage = "/og-card.png"
    [opengraph.twitter]
        site = "praynpush"
        card = "summary_large_image"
